version: '1'
services:
  nginx-react:
    container_name: next_boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    restart: always
